[git]
conventional_commits = true
filter_unconventional = true

[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}- {{ commit.message }}
{% endfor %}
{% endfor %}
"""
